### ISSUE TITLE
Magnetic synchronization causes segmentation fault

### ISSUE THREAD

**Issue by Chuban** [stevengj/meep#309]
I'm trying to run one of the MEEP examples and output a synchronized magnetic field.  Whenever I try to call synchronized_magnetic(), I get a segmentation fault.  The code that I'm trying to run is:

```
import meep as mp

cell = mp.Vector3(16, 8, 0)

geometry = [mp.Block(mp.Vector3(1e20, 1, 1e20),
                     center=mp.Vector3(0, 0),
                     material=mp.Medium(epsilon=12))]

sources = [mp.Source(mp.ContinuousSource(frequency=0.15),
                     component=mp.Ez,
                     center=mp.Vector3(-7,0))]

pml_layers = [mp.PML(1.0)]

resolution = 10

sim = mp.Simulation(cell_size=cell,
                    boundary_layers=pml_layers,
                    geometry=geometry,
                    sources=sources,
                    resolution=resolution)

sim.run(mp.synchronized_magnetic(mp.output_bfield_y),
        until=10)
```

This works fine if I omit the mp.synchronized_magnetic() call.

I installed MEEP from conda using the instructions in the documentation.  I'm using Ubuntu 16.04.  The exact error message is:

```
python example.py
-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 16 x 8 x 0 with resolution 10
     block, center = (0,0,0)
          size (1e+20,1,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (12,12,12)
time for set_epsilon = 0.0905111 s
-----------
creating output file "./example-by-000000.00.h5"...
Segmentation fault (core dumped)
```

Any advice would be appreciated.  Is there anyway to get more debug information?

**Comment by ChristopherHogan** [comment]
The segmentation fault isn't specific to python; I see the same error in a similar scheme simulation:
```scheme
(set! geometry-lattice (make lattice (size 16 8 no-size)))

(set! geometry (list
                (make block
                  (center 0 0 0)
                  (size infinity 1 infinity)
                  (material (make medium (epsilon 12))))))

(set! sources (list
               (make source
                 (src (make continuous-src (frequency 0.15)))
                 (component (meep-component-Ez))
                 (center -7 0 0))))

(set! pml-layers (list (make pml (thickness 1.0))))

(set! resolution 10)

(run-until 10 (synchronized-magnetic output-bfield-y))
```
The issue is that `memcpy` is called with a NULL argument in `energy_in_flux.cpp:fields_chunk::restore_component`, line 136 when `c = meep::By`.  Maybe @stevengj  can tell us if the usage of `synchronized_magnetic` looks correct in these examples.

**Comment by oskooi** [comment]
This error is not related to Meep but rather to the common mistake of passing the _result_ of a function to the run function rather than the function itself. This is described further in the [documentation](http://meep.readthedocs.io/en/latest/The_Run_Function_Is_Not_A_Loop/).

A simple fix would be:

```py
sim.run(lambda sim: mp.synchronized_magnetic(mp.output_bfield_y), until=10)
```
or

```scm
(run-until 10 (lambda () (synchronized-magnetic output-bfield-y)))
```
Unfortunately, the [documentation for this feature](http://meep.readthedocs.io/en/latest/Synchronizing_the_Magnetic_and_Electric_Fields/) is incorrect, which is what likely lead to this issue, and will be updated shortly.
