### ISSUE TITLE
computing mode coefficients of eigenmodes with negative wavevector components

### ISSUE THREAD

**Issue by oskooi** [stevengj/meep#476]
There doesn't seem to be a way to compute the mode coefficients of eigenmodes with *negative* wavevector components (i.e., diffraction orders with *negative* angles) given the current framework of `get_eigenmode_coefficients`. The [binary grating example tutorial](https://meep.readthedocs.io/en/latest/Python_Tutorials/Mode_Decomposition/#diffraction-spectrum-of-a-binary-grating) involved a normally incident source where the positive diffraction orders (i.e., those with `m `> 0) are equivalent to the negative orders by symmetry. This saves a factor of 2 in the computation which is nice. However for an oblique source which breaks the symmetry, it is necessary to compute the diffraction orders with negative angles. This may involve modifying `get_eigenmode_coefficients` to operate on modes with negative wavevector components. Currently, the wavevector components of the modes are always non negative.

**Comment by oskooi** [comment]
As an example based on the binary grating tutorial, an oblique planewave pulsed source with center frequency `fcen` and rotation angle `theta` (in radians, counter clockwise about y-axis) would correspond to a `k_point` of `mp.Vector3(math.cos(theta),math.sin(theta),0).scale(fcen)`. Since the mode monitor spans the entire length of the computational cell in the y-direction, the y-component of the mode's **k** wavevector (computed by `get_eigenmode_coefficients`) will therefore be exactly equivalent to the y-component of `k_point` (i.e., `math.sin(theta)*fcen`). Currently, the y-component of the modes are always non-negative (since `theta` >= 0). However, when `k_point` is non zero, it becomes necessary to also compute modes with the negative y-component (i.e., `-math.sin(theta)*fcen`). These correspond to diffraction orders with negative angles. In general, the mode coefficients of the diffraction orders with positive and negative angles are not the same. This can be used as part of the validation.

**Comment by stevengj** [comment]
Suppose the Bloch wavevector is `K`, and the primitive reciprocal lattice vector is `G` (`= 1/period` in our units).   Now you do the `acos` calculation and get a value `k`.  This is actually just the absolute value of the wavevector, since `acos` always returns a positive result.   One of the two must be true:

* positive diffracted order: `k = K + m*G` for some nonnegative integer `m`
* negative diffracted order: `-k = K - m*G` for some nonnegative integer `m`.

So, to get the right sign, just compute `(k-K)/G` and `(k+K)/G` and see which one is closer to an nonnegative integer — if it is the former, then use `+k`, if the latter, then `-k`.

**Comment by oskooi** [comment]
What about the case when `k = K - m*G` for some nonnegative integer `m`? This should also correspond to a *positive* diffracted order even though it involves `-m`.
