### ISSUE TITLE
amp-func and eigenmode-source

### ISSUE THREAD

**Issue by acerjan** [stevengj/meep#532]
In the user reference, it states that an amp-func can be specified for an eigenmode-source, but I'm having a couple of questions / issues with this.

1) is this functionality currently working? I've successfully specified amp-func for an ordinary source, but when I change to an eigenmode-source, meep quits with the message "ERROR: In procedure meep-fields-add-eigenmode-source: No matching method for generic function `meep_fields_add_eigenmode_source'"

2) When solving for an eigenmode-source with a non-zero eig-kpoint, does the mode that MPB returns, u_(n,k) (r), contain the factor of e^(i k r)? Or is it only the Bloch mode u_(n,k) (r)? This is not clear in the user reference.

Thanks!

**Comment by stevengj** [comment]
To answer your second question, this was a bug that is fixed by #499: the mode was *supposed* to be the actual field, i.e. including the  eⁱᵏʳ factor, but this was missing; we didn't notice it because we had mainly used this feature for constant-cross-section waveguide modes where this factor was unity.

**Comment by acerjan** [comment]
Ok. It looks like #499 is not yet merged and does not include any documentation changes. Is someone already working on updating the documentation to make this clear or would you like me to do it?

**Comment by stevengj** [comment]
#499 is now merged; a documentation PR would be welcome, thanks!
