### ISSUE TITLE
Inconsistent length scale of imported coupler.gds in MEEP

### ISSUE THREAD

**Issue by centaure** [stevengj/meep#555]
In the [coupler.gds](https://github.com/stevengj/meep/blob/master/python/examples/coupler.gds) example, the height * width of the cell is 34400 um * 8000 um. But when running the MEEP [example python script](https://github.com/stevengj/meep/blob/master/python/examples/coupler.py), the size is taken as 34.4 um * 8 um (since we use a length scale of 1 um in the MEEP example). 

We should stick to the same length scale.

**Comment by oskooi** [comment]
Note that the unit distance in the GDS file is defined as `0.001` μm. The cell (layer `0`) has dimensions `34400` x `8000` which is indeed `34.4` μm x `8` μm. However, the cell defined in Meep by `examples/coupler.py` is `34.4` x `7.8`:

```
Using MPI version 3.0, 1 processes
-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 34.4 x 7.8 x 0 with resolution 25
     prism, center = (-9.09425,1.31149,0)
          height 0, axis (0,0,1), 174 vertices:
...
```
The *y* dimension of the cell should be exactly `8.0`. This discrepancy may be due to a bug in [libGDSII](https://github.com/HomerReid/libGDSII).

@HomerReid

**Comment by centaure** [comment]
I think you may be confusing database units with the actual dimensions (see [1]). If you open coupler.gds in KLayout or L-Edit, you will see that the width * height are 34400 um * 8000 um (I am attaching a screenshot from KLayout, with the reference length of 2000 um, given by KLayout, shown in its bottom left).

[1] https://www.klayout.de/forum/discussion/447/data-base-units

![coupler-klayout](https://user-images.githubusercontent.com/1370619/47612634-13360380-da3c-11e8-959a-e11980fe00fa.PNG)

**Comment by centaure** [comment]
In database units (i.e. 0.001 um), you should be getting 1000 times more points in the x and y directions as shown in this screenshot for Layer 0 (using KLayout editor).

<img width="1438" alt="screen shot 2018-10-28 at 12 16 19 pm" src="https://user-images.githubusercontent.com/1370619/47620778-86c32980-daab-11e8-9a11-208947480f28.png">

**Comment by HomerReid** [comment]
Thanks for the input. The confusion seems to have arisen because the default in `libGDSII` had been to report lengths in units of millimeters by default, which is more appropriate for RF applications, while for photonics it seems more natural to use microns. As of the latest libGDSII master-branch commit (c5cc55f) this is now the default, and meep#585 the various GDSII files (including `coupler.gds`) have been rescaled appropriately. When you have a chance, please confirm that things make more sense now.
