### ISSUE TITLE
Feature Request: Python Simulation Center

### ISSUE THREAD

**Issue by smartalecH** [stevengj/meep#590]
It would be nice to be able to center the simulation domain at any arbitrary coordinate within the python interface.

**Comment by soamaven** [comment]
The origin is set when the structure is initialized. Looks like the `set_origin()` method of `grid_volume` is exposed by swig, but the simulation doesn't store a grid volume as a property, just the structure, which however does store the `grid_volume`.

Maybe you could try something along the lines of `sim.structure.gv.set_origin(mp.Vector3())` but i'm not sure that the fields, monitors, etc. will move with the structure grid volume. It might, it looks like flux monitors internally store their coordinates, it looks like `fields` requires the `structure.gv` but it is referenced rather than copied.

I am a sophmore C++ coder, but I've convinced myself its worth a try setting the origin after initializing the simulation/structure

**Comment by stevengj** [comment]
This is supported in Scheme via the `geometry-center` parameter, but there is no analogous support yet in Python.

In particular, when the `structure` is initialized in Scheme, it calls [shift_origin](https://github.com/stevengj/meep/blob/41802ae34dae36bb7ae92868d2ee7a3693a8483a/scheme/structure.cpp#L1491-L1492) to shift the origin to the provided `center`, and it also [sets the libctlgeom `geometry_center`](https://github.com/stevengj/meep/blob/41802ae34dae36bb7ae92868d2ee7a3693a8483a/scheme/structure.cpp#L1451-L1452) so that the geometric objects are interpreted relative to this center.

The Python `Simulation` object actually [has a `geometry_center` field](https://github.com/stevengj/meep/blob/master/python/simulation.py#L480), but it is currently unused.  To enable this feature in Python, you'd want to do three things:

* Add a `geometry_center=Vector3()` parameter to the `Simulation` object's `__init__` function so that you could pass this parameter when constructing your `Simulation`.

* Use the `self.geometry_center` when creating the grid volume [here](https://github.com/stevengj/meep/blob/master/python/simulation.py#L609) by adding a `shift_origin` call similar to Scheme.

* Modify `set_materials_from_geometry`  in libmeep geom to take a `center` argument and to set `geometry_center = center` [after calling `geom_initialize()`](https://github.com/stevengj/meep/blob/41802ae34dae36bb7ae92868d2ee7a3693a8483a/libmeepgeom/meepgeom.cpp#L1552), similar to the Scheme code above.  Then modify the `Simulation` object to pass `self.geometry_center` to libmeepgeom via this parameter, and modify the other code calling libmeepgeom as needed.
